#!/bin/sh
git_exists_branch ()
{
	branch_name=$1
	git show-branch $branch_name > /dev/null 2> /dev/null
	if [ $? -eq 0 ]; then
		echo "branch exists"
	else
		echo "branch does not exist"
	fi
}

git_exists_branch
